import 'package:flutter/material.dart';
import 'package:flutter_fast_ui_white/flutter_fast_ui_white.dart';
import 'package:fourle/front_page.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return FastThemeScope(
        accentColor: Colors.green,
        themeMode: ThemeMode.dark,
        builder: (context, lightTheme, darkTheme, mode) {
          final seed = Uri.base.queryParameters['s'];
          return MaterialApp(
            title: '四字熟語le',
            theme: lightTheme,
            darkTheme: darkTheme,
            themeMode: mode,
            home: FrontPage(
              initialSeed: int.tryParse(seed ?? ""),
            ),
          );
        });
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black12,
      body: Center(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text("四字熟語LE",
                  style: TextStyle(fontSize: 30, color: Colors.white)),
            ),
            Expanded(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  SizedBox(
                      width: 500,
                      child: GridView.count(
                        crossAxisCount: 8,
                        children: kanjis
                            .map((e) => Card(
                                  color: selectColor(e),
                                  child: Center(
                                      child: Text(
                                    e,
                                    style: TextStyle(
                                        fontSize: 15, color: Colors.white),
                                  )),
                                ))
                            .toList(),
                      )),
                  const SizedBox(width: 50),
                  SizedBox(
                    width: 500,
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        InputRow(words: [
                          "心",
                          "機",
                          "一",
                          "転"
                        ], colors: [
                          wordleYellow,
                          wordleGrey,
                          wordleYellow,
                          wordleGrey
                        ]),
                        InputRow(words: [
                          "一",
                          "言",
                          "居",
                          "士"
                        ], colors: [
                          wordleGreen,
                          wordleGrey,
                          wordleGrey,
                          wordleGrey
                        ]),
                        InputRow(),
                        InputRow(),
                        InputRow(),
                        InputRow(),
                      ],
                    ),
                  )
                ],
              ),
            )
          ],
        ),
      ),
    );
  }

  Color selectColor(String w) {
    switch (w) {
      case "心":
        return wordleYellow;
      case "機":
      case "転":
      case "居":
      case "士":
        return wordleDark;
      case "一":
        return wordleGreen;
      default:
        return Colors.white.withOpacity(0.5);
    }
  }

  Color wordleGrey = Color(0xFF3A3A3C);
  Color wordleGreen = Color(0xFF538D4E);
  Color wordleYellow = Color(0xFFB59F3B);
  Color wordleDark = Color(0xFF3A3A3C);

  Widget InputRow({List<String>? words, List<Color?>? colors}) {
    final w = words ?? ["", "", "", ""];
    final c = colors ?? [null, null, null, null];
    return Row(
      children: [
        InputSquare(word: w[0], color: c[0]),
        InputSquare(word: w[1], color: c[1]),
        InputSquare(word: w[2], color: c[2]),
        InputSquare(word: w[3], color: c[3]),
      ],
    );
  }

  Widget InputSquare({String word = "", Color? color}) {
    return SizedBox(
      width: 100,
      height: 100,
      child: Card(
        shape: RoundedRectangleBorder(
          side: BorderSide(
            color: color ?? wordleGrey,
            width: 2,
          ),
        ),
        color: color ?? Colors.transparent,
        child: Center(
          child: Text(
            word,
            style: TextStyle(
                fontSize: 40, color: Colors.white, fontWeight: FontWeight.bold),
          ),
        ),
      ),
    );
  }

  final kanjis = [
    "一",
    "之",
    "無",
    "不",
    "天",
    "三",
    "大",
    "心",
    "万",
    "風",
    "人",
    "千",
    "行",
    "言",
    "山",
    "生",
    "雲",
    "水",
    "自",
    "馬",
    "百",
    "中",
    "子",
    "月",
    "地",
    "明",
    "白",
    "日",
    "衣",
    "金",
    "同",
    "意",
    "花",
    "竜",
    "知",
    "玉",
    "雨",
    "下",
    "気",
    "然",
    "長",
    "文",
    "多",
    "世",
    "面",
    "木",
    "相",
    "虎",
    "魚",
    "高",
    "目",
    "落",
    "食",
    "石",
    "上",
    "苦",
    "断",
    "四",
    "有",
    "道",
    "十",
    "頭",
    "流",
    "事",
    "光",
    "満",
    "秋",
    "利",
    "思",
    "成",
    "朝",
    "名",
    "死",
    "海",
    "放",
    "五",
    "才",
    "里",
    "学",
    "和",
    "者",
    "立",
    "草",
    "身",
    "清",
    "悪",
    "髪",
    "平",
    "八",
    "法",
    "前",
    "口",
    "義",
    "家",
    "国",
    "後",
    "転",
    "空",
    "夜",
    "実",
    "美",
    "九",
    "安",
    "南",
    "分",
    "君",
    "影",
    "牛",
    "二",
    "書",
    "遠",
    "尺",
    "色",
    "土",
    "酒",
    "足",
    "直",
    "孤",
    "車",
    "絶",
    "外",
    "青",
    "難",
    "乱",
    "手",
    "力",
    "小",
    "異",
    "変",
    "飛",
    "神",
    "年",
    "楽",
    "望",
    "離",
    "物",
    "情",
    "半",
    "発",
    "正",
    "随",
    "開",
    "七",
    "動",
    "温",
    "理",
    "非",
    "往",
    "鳳",
    "春",
    "門",
    "先",
    "円",
    "愛",
    "命",
    "方",
    "交",
    "暮",
    "鶴",
    "士",
    "火",
    "来",
    "善",
    "精",
    "志",
    "徳",
    "常",
    "戦",
    "滅",
    "語",
    "鳥",
    "失",
    "合",
    "鬼",
    "虚",
    "折",
    "河",
    "墨",
    "為",
    "厚",
    "兎",
    "代",
    "機",
    "見",
    "曲",
    "肉",
    "挙",
    "果",
    "耳",
    "沈",
    "寒",
    "体",
    "骨",
    "独",
    "声",
    "筆",
    "在",
    "珠",
    "首",
    "氷",
    "寸",
    "古",
    "波",
    "良",
    "進",
    "易",
    "貴",
    "堅",
    "軽",
    "散",
    "黄",
    "重",
    "時",
    "如",
    "奇",
    "雪",
    "歩",
    "野",
    "用",
    "以",
    "内",
    "鶏",
    "眉",
    "暗",
    "達",
    "得",
    "切",
    "窮",
    "狼",
    "深",
    "武",
    "過",
    "暴",
    "角",
    "全",
    "新",
    "香",
    "華",
    "味",
    "六",
    "刀",
    "忠",
    "紅",
    "夢",
    "烏",
    "起",
    "薪",
    "笑",
    "博",
    "聞",
    "俗",
    "固",
    "至",
    "形",
    "帰",
    "眼",
    "功",
    "田",
    "狗",
    "入",
    "視",
    "帯",
    "残",
    "致",
    "懸",
    "鳴",
    "節",
    "末",
    "字",
    "説",
    "歌",
    "北",
    "闊",
    "求",
    "感",
    "歯",
    "老",
    "胆",
    "勇",
    "浮",
    "問",
    "両",
    "顔",
    "鉄",
    "奔",
    "倒",
    "羊",
    "犬",
    "塵",
    "解",
    "端",
    "量",
    "居",
    "夫",
    "破",
    "抜",
    "々",
    "兵",
    "狐",
    "阿",
    "刻",
    "根",
    "定",
    "慮",
    "斗",
    "露",
    "賢",
    "報",
    "主",
    "観",
    "翼",
    "通",
    "剣",
    "雄",
    "亡",
    "飲",
    "堂",
    "恩",
    "論",
    "昧",
    "呑",
    "守",
    "己",
    "談",
    "寡",
    "磨",
    "信",
    "張",
    "従",
    "桃",
    "蛇",
    "作",
    "礼",
    "公",
    "永",
    "霜",
    "即",
    "路",
    "葉",
    "反",
    "念",
    "本",
    "鼎",
    "能",
    "樹",
    "枝",
    "英",
    "強",
    "当",
    "急",
    "城",
    "回",
    "息",
    "故",
    "因",
    "出",
    "謀",
    "質",
    "枯",
    "豪",
    "舌",
    "連",
    "剛",
    "浅",
    "毛",
    "星",
    "屋",
    "哀",
    "走",
    "栄",
    "斉",
    "所",
    "衆",
    "腹",
    "疾",
    "薄",
    "麗",
    "揚",
    "化",
    "是",
    "舟",
    "臣",
    "舞",
    "好",
    "縦",
    "応",
    "句",
    "横",
    "喜",
    "柳",
    "極",
    "顧",
    "女",
    "真",
    "枕",
    "到",
    "仏",
    "画",
    "垂",
    "勤",
    "双",
    "怪",
    "音",
    "喪",
    "尾",
    "勝",
    "羈",
    "穿",
    "低",
    "友",
    "微",
    "投",
    "近",
    "途",
    "盗",
    "雷",
    "禍",
    "群",
    "活",
    "怨",
    "冠",
    "源",
    "林",
    "富",
    "桑",
    "快",
    "鬱",
    "簡",
    "憂",
    "伝",
    "索",
    "結",
    "巧",
    "塗",
    "傾",
    "徹",
    "臥",
    "壁",
    "戒",
    "李",
    "様",
    "燕",
    "民",
    "客",
    "閑",
    "間",
    "聖",
    "疑",
    "伏",
    "轍",
    "読",
    "黒",
    "別",
    "福",
    "順",
    "吐",
    "蘭",
    "逆",
    "羅",
    "布",
    "梁",
    "今",
    "素",
    "陰",
    "鼠",
    "竹",
    "爛",
    "秀",
    "元",
    "越",
    "識",
    "左",
    "私",
    "兼",
    "悲",
    "覆",
    "容",
    "煙",
    "蒼",
    "乗",
    "退",
    "仁",
    "忍",
    "西",
    "対",
    "陽",
    "病",
    "指",
    "労",
    "災",
    "盛",
  ];
}
